name: dockerfile is updated

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'

env:
  REMOTE_REPO: "domainaware/parsedmarc"
  
jobs:
  update-docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - uses: ./.github/actions/get-last-release-version
      id: release-infos
      with:
        REPO: ${{ env.REMOTE_REPO }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: ./.github/actions/build
      if: ${{ steps.release-infos.outputs.version != '' }}
      with:
        VERSION: ${{ steps.release-infos.outputs.version }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}