name: dockerfile is updated

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'

env:
  REMOTE_REPO: "domainaware/parsedmarc"
  
jobs:
  update-docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: get last release
      id: release-infos
      uses: actions/github-script@v7.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const REMOTE_REPO = process.env.REMOTE_REPO;

          const latestRelease = await github.rest.repos.getLatestRelease({
              owner: REMOTE_REPO.split("/")[0],
              repo: REMOTE_REPO.split("/")[1],
          });

          const latestReleaseVersion = latestRelease.data.tag_name;
          core.setOutput('version', latestReleaseVersion);

    - uses: ./.github/actions/build
      if: ${{ steps.release-infos.outputs.version != '' }}
      with:
        VERSION: ${{ steps.release-infos.outputs.version }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}