name: dockerfile is updated

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'

env:
  REMOTE_REPO: "domainaware/parsedmarc"
  
jobs:
  update-docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

    - uses: ./.github/actions/get-last-release-version
      id: release-infos
      with:
        REPO: ${{ env.REMOTE_REPO }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: ./.github/actions/build
      if: ${{ steps.release-infos.outputs.version != '' }}
      with:
        VERSION: ${{ steps.release-infos.outputs.version }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}